name: Publish Ruby Images

on:
  schedule:
    # Every Sunday at 0600 UTC
    - cron: "0 6 * * 0"
  push:
    branches:
      - main

env:
  IMAGE_NAME: ruby-jemalloc

jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.4.10, 2.5.8, 2.7.2]

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image for Ruby ${{ matrix.ruby-version }}
        run: docker build -t $IMAGE_NAME --build-arg RUBY_VERSION=${{ matrix.ruby-version }} .

      - name: Push images to GitHub Container Registry
        run: |
          IMAGE_ID=mediapingllc/$IMAGE_NAME
          docker tag $IMAGE_NAME $IMAGE_ID:${{ matrix.ruby-version }}
          docker push $IMAGE_ID:${{ matrix.ruby-version }}
