name: Publish Ruby Images

on:
  schedule:
    # The first of the month at 1:03am UTC
    - cron: "0 * * * *"
  push:
    branches:
      - main

env:
  IMAGE_NAME: ruby-jemalloc

jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.4.10, 2.5.9, 2.6.10]
        include:
          - ruby-version: 2.4.10
          - ruby-version: 2.5.9
          - ruby-version: 2.6.10

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image for Ruby ${{ matrix.ruby-version }}
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            RUBY_VERSION=${{ matrix.ruby-version }}
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: mediapingllc/ruby-jemalloc:${{ matrix.ruby-version }}
