name: Publish Ruby Images

on:
  schedule:
    # Every Sunday at 0600 UTC
    - cron: "0 6 * * 0"
  push:
    branches:
      - main

env:
  IMAGE_NAME: ruby-jemalloc

jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.4.10, 2.5.8, 2.5.9, 2.6.6, 2.6.7, 2.7.2, 2.7.3]
        include:
          - ruby-version: 2.4.10
            bundler-version: 1.17.3
          - ruby-version: 2.5.8
            bundler-version: 1.17.3
          - ruby-version: 2.5.9
            bundler-version: 1.17.3
          - ruby-version: 2.6.6
            bundler-version: 2.2.15
          - ruby-version: 2.6.7
            bundler-version: 2.2.15
          - ruby-version: 2.7.2
            bundler-version: 2.2.15
          - ruby-version: 2.7.3
            bundler-version: 2.2.15

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image for Ruby ${{ matrix.ruby-version }}
        run: docker build -t $IMAGE_NAME --build-arg RUBY_VERSION=${{ matrix.ruby-version }} --build-arg BUNDLER_VERSION=${{ matrix.bundler-version }} .

      - name: Push images to GitHub Container Registry
        run: |
          IMAGE_ID=mediapingllc/$IMAGE_NAME
          docker tag $IMAGE_NAME $IMAGE_ID:${{ matrix.ruby-version }}
          docker push $IMAGE_ID:${{ matrix.ruby-version }}
