name: Publish Ruby Images

on:
  schedule:
    # Every Sunday at 0600 UTC
    - cron: "0 6 * * 0"
  push:
    branches:
      - main

env:
  IMAGE_NAME: ruby-jemalloc

jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.4.10, 2.5.8, 2.5.9]
        include:
          - ruby-version: 2.4.10
          - ruby-version: 2.5.8
          - ruby-version: 2.5.9

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image for Ruby ${{ matrix.ruby-version }}
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args:
            - RUBY_VERSION=${{ matrix.ruby-version }}
            - BUNDLER_VERSION=${{ matrix.bundler-version }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: $IMAGE_NAME $IMAGE_ID:${{ matrix.ruby-version }}
